export const INCREMENT = 'COUNTER_INCREMENT';
export const INCREMENT_ASYNC = 'COUNTER_INCREMENT_ASYNC';

export const START_TIMER = 'COUNTER_START_TIMER';
export const START_TIMER_ASYNC = 'COUTNER_START_TIMER_ASYNC';
