export const INCREMENT = 'COUNTER_INCREMENT';
export const INCREMENT_ASYNC = 'COUNTER_INCREMENT_ASYNC';
export const DECREMENT = 'COUNTER_DECREMENT';
export const DECREMENT_ASYNC = 'COUNTER_DECREMENT_ASYNC';

export const START_TIMER = 'COUNTER_START_TIMER';
export const START_TIMER_ASYNC = 'COUTNER_START_TIMER_ASYNC';

export const GET_TIME = 'COUNTER_GET_TIME';
